feat(tangle-cloud): Configure Layout, Network, and Wallet
tangle-network/dapp pull request #2651
Opened 2024-11-12 20:13 UTC by AtelyPham

## Summary of changes

- **MAIN WORK:** Establish a new library named `tangle-shared-ui` to facilitate the sharing of UI components and logic hooks between the Tangle dApp and Tangle Cloud.
- Implement the layout, including a header, footer, and a sidebar for Tangle Cloud, featuring a dropdown menu for role selection.
- Remove the hardcoded provider type from `useSubstrateExplorerUrl` to resolve an encoding issue that caused the dApp to freeze when connecting to the EVM wallet https://github.com/tangle-network/dapp/commit/ae33481147135cedd05735000a34ae7e220e7b66.
- Incorporate a connected accounts check to ensure accounts are always available before initializing the Polkadot API https://github.com/tangle-network/dapp/commit/db5fec2eaa615ce60e4c65bc3b5ddaa6b9efc1a5.
- Add the missing target typed chain ID to the "try again" function to ensure proper wallet connectivity when users click on it https://github.com/tangle-network/dapp/commit/dcd8bb45f172a33241674d172f636933ee2946c7.

### Proposed area of change

_Put an `x` in the boxes that apply._

- [x] `apps/tangle-dapp`
- [x] `apps/tangle-cloud`
- [x] `libs/webb-ui-components`

### Associated issue(s)

_Specify any issues that can be closed from these changes (e.g. `Closes #233`)._

- Closes https://github.com/tangle-network/dapp/issues/2558

### Screen Recording

_If possible provide screenshots and/or a screen recording of proposed change._

https://github.com/user-attachments/assets/5052dfaa-2593-4071-9354-c9e652db979c

2024-11-12 21:19 UTC, yurixander requested changes

2024-11-12 21:19 UTC, yurixander commented on libs/tangle-shared-ui/src/types/bridge.ts
> +  /** The tx executed successfully */
```suggestion
```

2024-11-12 21:19 UTC, yurixander commented on libs/tangle-shared-ui/src/types/bridge.ts
> +  /** The tx is being initialized */
```suggestion
```

2024-11-12 21:19 UTC, yurixander commented on libs/tangle-shared-ui/src/types/bridge.ts
> +  /** The tx is being initialized */
```suggestion
```

2024-11-12 21:19 UTC, yurixander commented on libs/webb-ui-components/src/components/SideBar/SideBar.tsx
> +              </IconButton>
This fixes #2600

2024-11-12 21:19 UTC, yurixander commented on libs/webb-ui-components/src/utils/getDisplayAccountAddress.ts
The real purpose of this function is to encode a Substrate address if a SS58 prefix is provided, maybe `tryEncodeSubstrateAddress` or similar would be a better name?

2024-11-13 04:38 UTC, AtelyPham commented on libs/tangle-shared-ui/src/components/UpdateMetadataButton/index.ts
When developing reusable UI components, it's conventional to export each one as its own module. This allows for direct imports, such as `import Button from "@webb-ui-components/components/Alert"`, rather than importing the entire library, which benefits tree shaking. 

Organizing components as separate modules in a directory makes building the library easier. However, since we are not currently publishing the library, it's acceptable to use a file for standalone components. I just wanted to clarify this reasoning.

2024-11-13 05:01 UTC, drewstone commented
Looks great @AtelyPham ! In the next PR let's turn the `Operator` `Deployer` purple button in the sidebar into a proper looking dropdown, right now it looks like a button. You can deviate from design if you have intuition something is off!

2024-11-13 05:01 UTC, merged